version: "3.3"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      - CONDA_ENV=hackathon_env
    volumes:
      - /home/g2004_01013/sqlite_data:/app/database  # Теперь путь правильный
